# Generated by Django 5.2.17 on 2026-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Security', 'Security'), ('DevOps', 'DevOps'), ('Mobile', 'Mobile')], max_length=50)),
                ('desc', models.TextField()),
                ('tech', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
