# Generated by Django 5.2.17 on 2026-08-09 17:31

import django.core.validators
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'gif')), portfolio.validators.ImageFormatValidator(), portfolio.validators.MaxBytesValidator(5242880)]),
        ),
    ]
