# Generated by Django 5.2.17 on 2026-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_client_name_project_client_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Client rating from 1 to 5 stars.', null=True),
        ),
    ]
