# Generated by Django 5.2.17 on 2026-08-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars.')),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False, help_text='Only approved reviews are shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Review',
                'verbose_name_plural': 'Project Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
