# Generated by Django 5.2.17 on 2026-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='Full Stack Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
