# Generated by Django 5.2.17 on 2026-08-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
