export const SITE = {
  name: "Saroj Kumar Mahato",
  shortName: "SKM.DEV",
  role: "Backend Developer & Full Stack Engineer",
  tagline:
    "I build scalable, secure backend systems and full-stack web applications with Django, DRF, and React.",
  location: "Kathmandu, Nepal",
  email: "info@saroj01.com.np",
  phone: "+977-9807827561",
  github: "https://github.com/s-k-m1",
  linkedin: "https://linkedin.com/in/saroj-kumar-mahato",
  twitter: "https://x.com/skm",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  description:
    "Backend Developer & Full Stack Engineer — Saroj Kumar Mahato builds scalable, secure APIs and web applications with Django, Django REST Framework, PostgreSQL, and React.",
  keywords: [
    "Saroj Kumar Mahato",
    "Backend Developer",
    "Backend Developer Nepal",
    "Django Developer",
    "Django REST Framework",
    "Python Backend Developer",
    "Full Stack Developer",
    "React Developer",
    "PostgreSQL Developer",
    "API Developer",
    "Freelance Backend Developer Nepal",
    "Portfolio",
  ] as string[],
};